import { TableColumn, TableRows } from "./tableProps";

export const dataColumns: TableColumn[] = [
  {
    name: "name",
    displayName: "Name",
    width: "20",
    isVisible: true,
  },
  {
    name: "phone",
    displayName: "Phone Number",
    width: "20",
    isVisible: true,
  },
  {
    name: "email",
    displayName: "Email",
    width: "40",
    isVisible: true,
  },
  {
    name: "address",
    displayName: "address",
    width: "20",
    isVisible: true,
  },
  {
    name: "postalZip",
    displayName: "Post Code",
    width: "20",
    isVisible: false,
  },
  {
    name: "region",
    displayName: "Region",
    width: "20",
    isVisible: false,
  },
  {
    name: "country",
    displayName: "Country",
    width: "20",
    isVisible: true,
  },
  {
    name: "list",
    displayName: "Shopping List Items",
    width: "20",
    isVisible: true,
  },
  {
    name: "organizations",
    displayName: "Organizations",
    width: "20",
    isVisible: false,
  },
];

export const dataRows: TableRows = [
  {
    name: "Hilary Sanders",
    phone: "(09) 4613 7681",
    email: "vel.est@mattiscras.ca",
    address: "128-9416 Tempor, Rd.",
    postalZip: "1775",
    region: "Rio de Janeiro",
    country: "Italy",
    list: 19,
    organizations: 6,
  },
  {
    name: "Xyla Wilson",
    phone: "(03) 4707 8245",
    email: "mauris@vivamusmolestie.net",
    address: "Ap #175-5635 Cursus Avenue",
    postalZip: "6445",
    region: "Konya",
    country: "Russian Federation",
    list: 1,
    organizations: 7,
  },
  {
    name: "Diana Juarez",
    phone: "(06) 0176 5414",
    email: "non.egestas.a@metus.ca",
    address: "Ap #447-2565 Ligula. Street",
    postalZip: "1216",
    region: "Mazowieckie",
    country: "Poland",
    list: 19,
    organizations: 8,
  },
  {
    name: "Palmer Shelton",
    phone: "(07) 9659 8163",
    email: "proin@pedeblandit.edu",
    address: "7580 Libero St.",
    postalZip: "7254",
    region: "Northern Territory",
    country: "United States",
    list: 15,
    organizations: 8,
  },
  {
    name: "Cathleen Frazier",
    phone: "(04) 7524 8444",
    email: "ut.cursus@inmipede.net",
    address: "4772 Nec, St.",
    postalZip: "4482",
    region: "West Nusa Tenggara",
    country: "Mexico",
    list: 11,
    organizations: 6,
  },
  {
    name: "Orla Levy",
    phone: "(06) 7156 9579",
    email: "aliquam@egestasascelerisque.edu",
    address: "385-8102 Enim Road",
    postalZip: "7022",
    region: "Tarapacá",
    country: "Nigeria",
    list: 5,
    organizations: 8,
  },
  {
    name: "Paloma Conway",
    phone: "(05) 0248 3053",
    email: "odio.sagittis@liberoatauctor.ca",
    address: "Ap #364-2902 Ac Road",
    postalZip: "8280",
    region: "Navarra",
    country: "Costa Rica",
    list: 1,
    organizations: 3,
  },
  {
    name: "Felicia Roach",
    phone: "(05) 1861 6155",
    email: "mauris.aliquam@netuset.ca",
    address: "2628 Dui Road",
    postalZip: "3437",
    region: "O'Higgins",
    country: "United States",
    list: 1,
    organizations: 5,
  },
  {
    name: "Kay Gay",
    phone: "(04) 3803 2405",
    email: "nulla.at@magnapraesent.com",
    address: "Ap #710-2682 Nunc Rd.",
    postalZip: "4332",
    region: "Morelos",
    country: "Turkey",
    list: 17,
    organizations: 4,
  },
  {
    name: "Cynthia Neal",
    phone: "(02) 3973 8778",
    email: "eleifend.cras@urnajustofaucibus.ca",
    address: "Ap #664-2627 Lorem Road",
    postalZip: "2913",
    region: "Rostov Oblast",
    country: "Italy",
    list: 17,
    organizations: 4,
  },
  {
    name: "Caesar Miranda",
    phone: "(07) 1321 4145",
    email: "convallis.ligula@ipsumleo.ca",
    address: "962-896 Fames Road",
    postalZip: "2817",
    region: "Ceará",
    country: "Pakistan",
    list: 3,
    organizations: 8,
  },
  {
    name: "Geraldine Fisher",
    phone: "(03) 7402 2263",
    email: "nisi.dictum@mollisduis.net",
    address: "P.O. Box 301, 6430 Suspendisse St.",
    postalZip: "2383",
    region: "Alajuela",
    country: "Sweden",
    list: 5,
    organizations: 7,
  },
  {
    name: "Macy Morrow",
    phone: "(01) 0414 2572",
    email: "tincidunt@magnis.com",
    address: "2783 Dapibus St.",
    postalZip: "6665",
    region: "Zachodniopomorskie",
    country: "Indonesia",
    list: 5,
    organizations: 5,
  },
  {
    name: "Leila Brennan",
    phone: "(04) 1716 8299",
    email: "cras@nullaeget.org",
    address: "6760 Iaculis Road",
    postalZip: "2328",
    region: "Colorado",
    country: "Indonesia",
    list: 3,
    organizations: 8,
  },
  {
    name: "Mercedes Hahn",
    phone: "(01) 1462 9712",
    email: "nunc.laoreet@utsagittis.co.uk",
    address: "194 Nibh Rd.",
    postalZip: "2154",
    region: "Niger",
    country: "Sweden",
    list: 3,
    organizations: 9,
  },
  {
    name: "Wade Riley",
    phone: "(02) 4262 7266",
    email: "penatibus.et@scelerisquenequesed.edu",
    address: "P.O. Box 658, 6843 Porttitor Rd.",
    postalZip: "9782",
    region: "Nunavut",
    country: "United States",
    list: 17,
    organizations: 1,
  },
  {
    name: "Kirsten Lang",
    phone: "(09) 8757 9580",
    email: "donec.porttitor.tellus@justonec.co.uk",
    address: "563-9234 Fames Street",
    postalZip: "9677",
    region: "Rio de Janeiro",
    country: "Vietnam",
    list: 7,
    organizations: 1,
  },
  {
    name: "Regina Dudley",
    phone: "(06) 0435 6573",
    email: "integer.mollis@in.ca",
    address: "P.O. Box 659, 8197 In Avenue",
    postalZip: "5856",
    region: "Special Capital Region of Jakarta",
    country: "Canada",
    list: 7,
    organizations: 9,
  },
  {
    name: "Kristen Holman",
    phone: "(01) 6405 5623",
    email: "elit.pharetra.ut@integervulputate.ca",
    address: "P.O. Box 866, 2768 Faucibus St.",
    postalZip: "2868",
    region: "Maharastra",
    country: "Canada",
    list: 5,
    organizations: 2,
  },
  {
    name: "Hayfa Robertson",
    phone: "(08) 9197 0117",
    email: "ullamcorper.viverra@erosproin.org",
    address: "237-1766 Nostra, Avenue",
    postalZip: "9365",
    region: "Alberta",
    country: "Nigeria",
    list: 11,
    organizations: 3,
  },
  {
    name: "Alexandra Buckley",
    phone: "(06) 7947 1613",
    email: "sapien.nunc.pulvinar@vestibulumut.org",
    address: "890-9562 Mus. St.",
    postalZip: "3131",
    region: "Leinster",
    country: "Spain",
    list: 5,
    organizations: 5,
  },
  {
    name: "Caryn Jacobs",
    phone: "(08) 6426 1897",
    email: "erat.etiam@imperdiet.edu",
    address: "P.O. Box 754, 5093 Dignissim. Rd.",
    postalZip: "8434",
    region: "Emilia-Romagna",
    country: "Italy",
    list: 5,
    organizations: 2,
  },
  {
    name: "Benedict Cochran",
    phone: "(01) 8824 9579",
    email: "diam.duis@lacusquisqueimperdiet.ca",
    address: "Ap #325-6681 Felis Ave",
    postalZip: "3439",
    region: "Lima",
    country: "Pakistan",
    list: 11,
    organizations: 1,
  },
  {
    name: "Kennan Patterson",
    phone: "(04) 4387 0832",
    email: "auctor.quis@vehiculapellentesque.net",
    address: "P.O. Box 567, 6278 Sed Ave",
    postalZip: "4194",
    region: "East Java",
    country: "Germany",
    list: 17,
    organizations: 9,
  },
  {
    name: "Brianna Faulkner",
    phone: "(06) 1723 2528",
    email: "tristique.aliquet@mi.edu",
    address: "504-1225 Purus, Ave",
    postalZip: "8187",
    region: "Gangwon",
    country: "Chile",
    list: 5,
    organizations: 3,
  },
];
